#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# SkyHanni ProGuard
# Minecraft 26.2 / Fabric / Kotlin 2.4.10
# ============================================================

PG="/opt/proguard/bin/proguard.sh"
JAVA="${JAVA_HOME:?JAVA_HOME is not set}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

IN="$ROOT/build/libs/SkyHanni-7.46.0-mc26.2.jar"
OUT="$ROOT/build/libs/SkyHanni-7.46.0-mc26.2-optimized.jar"
RULES="$ROOT/proguard-rules.pro"
LIBRARIES="$ROOT/libraries.txt"

GRADLE="${GRADLE_USER_HOME:-$HOME/.gradle}"
CACHE="$GRADLE/caches/modules-2/files-2.1"

# ============================================================
# Validation
# ============================================================

[[ -x "$PG" ]] || {
    echo "ERROR: ProGuard not found:"
    echo "  $PG"
    exit 1
}

[[ -f "$IN" ]] || {
    echo "ERROR: Input JAR not found:"
    echo "  $IN"
    exit 1
}

[[ -f "$RULES" ]] || {
    echo "ERROR: ProGuard rules not found:"
    echo "  $RULES"
    exit 1
}

[[ -f "$LIBRARIES" ]] || {
    echo "ERROR: libraries.txt not found, run the build task and remove the random lines:"
    echo "  $LIBRARIES"
    exit 1
}

[[ -f "$JAVA/jmods/java.base.jmod" ]] || {
    echo "ERROR: Invalid JAVA_HOME, try and install/download jmod:"
    echo "  $JAVA"
    exit 1
}

rm -f "$OUT"

# ============================================================
# Library handling
# ============================================================

LIB=()
declare -A SEEN

add() {
    local f="$1"

    [[ -f "$f" ]] || {
        echo "WARNING: library does not exist:"
        echo "  $f"
        return 0
    }

    f="$(realpath "$f")"

    # Never put the program JAR on the library path.
    [[ "$f" == "$(realpath "$IN")" ]] && return 0

    # Never use source/Javadoc artifacts.
    case "$f" in
        *-sources.jar|*-javadoc.jar|*-src.jar)
            return 0
            ;;
    esac

    # Exact path deduplication.
    [[ "${SEEN[$f]+x}" ]] && return 0

    SEEN["$f"]=1
    LIB+=("-libraryjars" "$f")

    echo "LIB: $f"
}

# ============================================================
# JDK
# ============================================================

echo
echo "== JDK =="

for module in \
    java.base \
    java.desktop \
    java.naming \
    java.security.jgss \
    java.management \
    java.logging \
    java.net.http \
    java.sql \
    java.xml \
    jdk.crypto.ec \
    jdk.management \
    jdk.unsupported
do
    [[ -f "$JAVA/jmods/$module.jmod" ]] &&
        add "$JAVA/jmods/$module.jmod"
done

# ============================================================
# Resolved Minecraft/Loom libraries
#
# libraries.txt was generated by the Gradle diagnostic task.
# Only real JAR files are accepted.
# ============================================================

echo
echo "== Minecraft / Loom libraries =="

while IFS= read -r f || [[ -n "$f" ]]; do

    # Remove CR from Windows-formatted files.
    f="${f%$'\r'}"

    # Trim leading/trailing whitespace.
    f="$(echo "$f" | xargs)"

    [[ -z "$f" ]] && continue

    case "$f" in
        *.jar)
            add "$f"
            ;;
    esac

done < "$LIBRARIES"

# ============================================================
# Direct Fabric dependencies
#
# These are included only if they weren't already present in
# libraries.txt.
# ============================================================

echo
echo "== Direct Fabric dependencies =="

add "$ROOT/build/libs/fabric-api-0.155.2+26.2.jar"
add "$ROOT/build/libs/fabric-language-kotlin-1.13.13+kotlin.2.4.10.jar"

# ============================================================
# Hypixel API
#
# IMPORTANT:
# This is the actual API JAR SkyHanni references.
#
# Do NOT use:
# build/libs/HypixelModAPI-1.0.2+build.1+mc26.1.jar
#
# That JAR is the Fabric implementation.
# ============================================================

echo
echo "== Hypixel API =="

HYPixel_API="$CACHE/net.hypixel/mod-api/1.0.2/2ad8cc0e370fc00d27540617817204019f911708/mod-api-1.0.2.jar"

if [[ -f "$HYPixel_API" ]]; then
    add "$HYPixel_API"
else
    echo "WARNING: Hypixel API not found at:"
    echo "  $HYPixel_API"
fi

# ============================================================
# Kotlin stdlib
# ============================================================

echo
echo "== Kotlin =="

KOTLIN_STDLIB=""

while IFS= read -r f; do

    [[ -f "$f" ]] || continue

    if jar tf "$f" 2>/dev/null |
        grep -q '^kotlin/jvm/internal/Intrinsics.class$'
    then
        KOTLIN_STDLIB="$f"
        break
    fi

done < <(
    find "$CACHE" \
        -type f \
        -name 'kotlin-stdlib-*.jar' \
        ! -name '*-sources.jar' \
        ! -name '*-javadoc.jar' \
        ! -name '*-src.jar' \
        -print 2>/dev/null |
    sort -V -r
)

if [[ -n "$KOTLIN_STDLIB" ]]; then
    add "$KOTLIN_STDLIB"
else
    echo "ERROR: Kotlin stdlib not found."
    exit 1
fi

# Kotlin reflection.
while IFS= read -r f; do
    [[ -f "$f" ]] || continue
    add "$f"
    break
done < <(
    find "$CACHE" \
        -type f \
        -name 'kotlin-reflect-*.jar' \
        ! -name '*-sources.jar' \
        ! -name '*-javadoc.jar' \
        ! -name '*-src.jar' \
        -print 2>/dev/null |
    sort -V -r
)

# ============================================================
# kotlinx-coroutines
# ============================================================

echo
echo "== Coroutines =="

COROUTINE=""

while IFS= read -r f; do

    [[ -f "$f" ]] || continue

    if javap -classpath "$f" kotlinx.coroutines.BuildersKt \
        2>/dev/null |
        grep -q 'runBlockingK\$default'
    then
        COROUTINE="$f"
        break
    fi

done < <(
    find "$CACHE" \
        -type f \
        \( \
            -name 'kotlinx-coroutines-core-*.jar' \
            -o -name 'kotlinx-coroutines-core-jvm-*.jar' \
        \) \
        ! -name '*-sources.jar' \
        ! -name '*-javadoc.jar' \
        ! -name '*-src.jar' \
        -print 2>/dev/null |
    sort -V
)

if [[ -n "$COROUTINE" ]]; then
    add "$COROUTINE"
else
    echo "ERROR: Compatible kotlinx-coroutines JAR not found."
    exit 1
fi

# ============================================================
# JetBrains annotations
# ============================================================

echo
echo "== JetBrains annotations =="

while IFS= read -r f; do

    [[ -f "$f" ]] || continue

    if jar tf "$f" 2>/dev/null |
        grep -q '^org/jetbrains/annotations/NotNull.class$'
    then
        add "$f"
        break
    fi

done < <(
    find "$CACHE" \
        -type f \
        \( \
            -name 'annotations-*.jar' \
            -o -name 'jetbrains-annotations-*.jar' \
        \) \
        ! -name '*-sources.jar' \
        ! -name '*-javadoc.jar' \
        ! -name '*-src.jar' \
        -print 2>/dev/null |
    sort -V -r
)

# ============================================================
# Optional ModMenu
# ============================================================

for f in \
    "$ROOT"/build/libs/modmenu-*.jar \
    "$ROOT"/build/libs/ModMenu-*.jar
do
    [[ -f "$f" ]] && add "$f"
done

# ============================================================
# Summary
# ============================================================

echo
echo "============================================================"
echo "SkyHanni ProGuard"
echo "============================================================"
echo "Java:       $JAVA"
echo "Input:      $IN"
echo "Output:     $OUT"
echo "Rules:      $RULES"
echo "Libraries:  $((${#LIB[@]} / 2))"
echo "============================================================"
echo

# ============================================================
# Run ProGuard
# ============================================================

"$PG" \
    "@$RULES" \
    -injars "$IN" \
    -outjars "$OUT" \
    "${LIB[@]}"

# ============================================================
# Verify
# ============================================================

if [[ ! -f "$OUT" ]]; then
    echo
    echo "ERROR: ProGuard finished without producing:"
    echo "  $OUT"
    exit 1
fi

echo
echo "============================================================"
echo "SUCCESS"
echo "============================================================"

ls -lh "$IN"
ls -lh "$OUT"

echo
echo "SHA256:"
sha256sum "$OUT"

echo
echo "Done."
